name: gsheet.action test
on: push

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - id: 'update_worksheet'
        uses: upenu/softdev-action@release # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: 1G1js6wp_h14deErOgZdd05Z1J6fzz-oXakubSbdttng
          worksheetTitle: Sheet1
          actor: ${{ github.actor }}
          repository: ${{ github.repository }}
          sha: ${{ github.sha }}
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
